package controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.Label;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class idleBaseController {
	@FXML
	private MenuItem menuCloseButton;
	@FXML
	private ImageView shit;
	@FXML
	private Label currentMoneyLabel;

	// Event Listener on MenuItem[#menuCloseButton].onAction
	@FXML
	public void closeWindow(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#shit].onMouseClicked
	@FXML
	public void startProgress(MouseEvent event) {
		// TODO Autogenerated
	}
}
